# 96
telegram:
  net: QiGi3
  layer: 4
  lr: 0.01
  BN_model: True    # sure
  self_loop: True
  jk: None


# 96
WikipediaNetwork/chameleon:
  dropout: 0.0  # 0.5(acc65), 0.0(acc75)
  net:
  layer:
  lr:
  BN_model:
  self_loop:
  jk:





#
cora_ml:
  net: QiGi3
  layer: 3
  lr: 0.01
  BN_model: False
  self_loop : True
  jk: None


#
dgl/pubmed:
  net:
  layer: 4
  lr:
  BN_model: False
  self_loop : True
  jk: 'max'